package com.museumheist.game;
import com.museumheist.game.entity.KeyItem; import com.museumheist.game.entity.PowerUp; import java.util.Arrays;
public class GameState {
 public enum Status{PLAYING,PAUSED,CLEARED,FAILED} public enum HotbarType{EMPTY,KEY,TREASURE}
 public static class HotbarSlot{private HotbarType type=HotbarType.EMPTY;private String keyCode="",label="";private int color,treasureIndex=-1;private void clear(){type=HotbarType.EMPTY;keyCode=label="";color=0;treasureIndex=-1;}public HotbarType getType(){return type;}public String getKeyCode(){return keyCode;}public String getLabel(){return label;}public int getColor(){return color;}public int getTreasureIndex(){return treasureIndex;}}
 private Status status=Status.PLAYING; private boolean[] treasures=new boolean[1]; private final HotbarSlot[] hotbar=new HotbarSlot[GameConfig.HOTBAR_SLOT_COUNT]; private final PowerUp.Type[] stored=new PowerUp.Type[GameConfig.POWER_UP_SLOT_COUNT]; private String failureReason=""; private float boostEnergy,powerUpSeconds,speedPotionSeconds; private boolean boosting; private PowerUp.Type activePowerUp;
 public GameState(){for(int i=0;i<hotbar.length;i++)hotbar[i]=new HotbarSlot();}
 public void reset(int count){status=Status.PLAYING;treasures=new boolean[Math.max(1,count)];for(HotbarSlot s:hotbar)s.clear();Arrays.fill(stored,null);failureReason="";boostEnergy=0;boosting=false;activePowerUp=null;powerUpSeconds=speedPotionSeconds=0;} public void reset(){reset(1);}
 public void update(float dt,boolean boost){update(dt,boost,1f);} public void update(float dt,boolean boost,float recovery){if(!isPlaying()){boosting=false;return;}if(powerUpSeconds>0){powerUpSeconds=Math.max(0,powerUpSeconds-dt);if(powerUpSeconds<=0)activePowerUp=null;}if(speedPotionSeconds>0)speedPotionSeconds=Math.max(0,speedPotionSeconds-dt);if(boost&&boostEnergy>0){boosting=true;boostEnergy=Math.max(0,boostEnergy-dt/GameConfig.BOOST_FULL_USE_SECONDS);}else{boosting=false;boostEnergy=Math.min(1,boostEnergy+dt*recovery/GameConfig.BOOST_CHARGE_SECONDS);}}
 public boolean isPlaying(){return status==Status.PLAYING;}public boolean isPaused(){return status==Status.PAUSED;}public boolean isCleared(){return status==Status.CLEARED;}public boolean isFailed(){return status==Status.FAILED;}public boolean hasTreasure(){return getCollectedTreasureCount()>0;}public boolean hasAllTreasures(){return getCollectedTreasureCount()>=treasures.length;}public int getTreasureCount(){return treasures.length;}public int getCollectedTreasureCount(){int c=0;for(boolean v:treasures)if(v)c++;return c;}public boolean isTreasureCollected(int i){return i>=0&&i<treasures.length&&treasures[i];}
 public boolean collectTreasure(int i){if(!isPlaying()||i<0||i>=treasures.length||treasures[i])return false;HotbarSlot s=firstEmpty();if(s==null)return false;treasures[i]=true;s.type=HotbarType.TREASURE;s.label="展品 "+(i+1);s.treasureIndex=i;return true;}public void collectTreasure(){collectTreasure(0);}
 public boolean hasKey(){for(HotbarSlot s:hotbar)if(s.type==HotbarType.KEY)return true;return false;}public boolean hasKey(String code){for(HotbarSlot s:hotbar)if(s.type==HotbarType.KEY&&s.keyCode.equals(code))return true;return false;}public void collectKey(){}
 public boolean collectKey(KeyItem item){if(item==null||!isPlaying())return false;if(hasKey(item.getKeyCode())){item.collect();return true;}HotbarSlot s=firstEmpty();if(s==null)return false;s.type=HotbarType.KEY;s.keyCode=item.getKeyCode();s.label=item.getLabel();s.color=item.getColor();item.collect();return true;}
 public boolean isHotbarFull(){return firstEmpty()==null;}public HotbarSlot[] getHotbar(){return hotbar;}public HotbarSlot getHotbarSlot(int i){return i>=0&&i<hotbar.length?hotbar[i]:null;}public boolean dropHotbarSlot(int i){HotbarSlot s=getHotbarSlot(i);if(s==null||s.type==HotbarType.EMPTY)return false;if(s.type==HotbarType.TREASURE&&s.treasureIndex>=0&&s.treasureIndex<treasures.length)treasures[s.treasureIndex]=false;s.clear();return true;}
 public void pause(){if(status==Status.PLAYING){status=Status.PAUSED;boosting=false;}}public void resumePlaying(){if(status==Status.PAUSED)status=Status.PLAYING;}public void togglePause(){if(status==Status.PLAYING)pause();else if(status==Status.PAUSED)resumePlaying();}public void clearLevel(){status=Status.CLEARED;}public void fail(String reason){status=Status.FAILED;failureReason=reason;boosting=false;}public String getFailureReason(){return failureReason;}
 public float getBoostEnergy(){return boostEnergy;}public boolean isBoosting(){return boosting;}public void addBoostEnergy(float a){boostEnergy=Math.min(1,Math.max(0,boostEnergy+a));}
 public void storePowerUp(PowerUp.Type t){for(int i=0;i<stored.length;i++)if(stored[i]==null){stored[i]=t;return;}}public boolean canStorePowerUp(){for(PowerUp.Type t:stored)if(t==null)return true;return false;}public int getStoredPowerUpCount(){int c=0;for(PowerUp.Type t:stored)if(t!=null)c++;return c;}public PowerUp.Type getStoredPowerUp(int i){return i>=0&&i<stored.length?stored[i]:null;}public PowerUp.Type getStoredPowerUp(){for(PowerUp.Type t:stored)if(t!=null)return t;return null;}
 public boolean useStoredPowerUp(){return useStoredPowerUp(0);}public boolean useStoredPowerUp(int i){if(!isPlaying()||i<0||i>=stored.length||stored[i]==null)return false;PowerUp.Type t=stored[i];stored[i]=null;compact();if(t==PowerUp.Type.DECOY||t==PowerUp.Type.JAMMER)return true;if(t==PowerUp.Type.SPEED){speedPotionSeconds=GameConfig.SPEED_POTION_SECONDS;return true;}activePowerUp=t;powerUpSeconds=GameConfig.POWER_UP_EFFECT_SECONDS;return true;}
 public PowerUp.Type getActivePowerUp(){return activePowerUp;}public float getPowerUpSeconds(){return powerUpSeconds;}public boolean isInvisible(){return activePowerUp==PowerUp.Type.CLOAK;}public boolean canPhaseThroughWalls(){return activePowerUp==PowerUp.Type.PHASE;}public boolean isJammingSecurity(){return activePowerUp==PowerUp.Type.JAMMER;}public boolean isSpeedPotionActive(){return speedPotionSeconds>0;}public float getSpeedPotionSeconds(){return speedPotionSeconds;}
 private HotbarSlot firstEmpty(){for(HotbarSlot s:hotbar)if(s.type==HotbarType.EMPTY)return s;return null;}private void compact(){int w=0;for(PowerUp.Type t:stored)if(t!=null)stored[w++]=t;while(w<stored.length)stored[w++]=null;}
}
