package com.museumheist.game.logic;
import android.graphics.RectF; import com.museumheist.game.entity.*; import com.museumheist.game.world.*;
public final class Collision { private Collision(){}
 public static void movePlayer(Player p,float dx,float dy,Level level,boolean phase){if(phase){p.setPosition(clamp(p.getX()+dx,level.getBounds().left+p.getRadius(),level.getBounds().right-p.getRadius()),clamp(p.getY()+dy,level.getBounds().top+p.getRadius(),level.getBounds().bottom-p.getRadius()));return;}int steps=Math.max(1,(int)Math.ceil(Math.max(Math.abs(dx),Math.abs(dy))/Math.max(4,p.getRadius()*.35f)));float sx=dx/steps,sy=dy/steps;for(int i=0;i<steps;i++){float nx=p.getX()+sx;if(!blocked(nx,p.getY(),p.getRadius(),level))p.setPosition(nx,p.getY());float ny=p.getY()+sy;if(!blocked(p.getX(),ny,p.getRadius(),level))p.setPosition(p.getX(),ny);}}
 private static boolean blocked(float x,float y,float r,Level level){RectF b=level.getBounds();if(x-r<b.left||x+r>b.right||y-r<b.top||y+r>b.bottom)return true;for(Wall w:level.getWalls())if(w.isBlocking()&&circleIntersectsRect(x,y,r,w.getBounds()))return true;for(Door d:level.getDoors())if(d.isBlocking()&&circleIntersectsRect(x,y,r,d.getBounds()))return true;return false;}
 public static boolean circleIntersectsRect(float x,float y,float r,RectF rect){float cx=clamp(x,rect.left,rect.right),cy=clamp(y,rect.top,rect.bottom),dx=x-cx,dy=y-cy;return dx*dx+dy*dy<=r*r;}
 public static boolean circleIntersectsLine(float x,float y,float r,float ax,float ay,float bx,float by){float vx=bx-ax,vy=by-ay,l=vx*vx+vy*vy,t=l<=.001f?0:((x-ax)*vx+(y-ay)*vy)/l;t=clamp(t,0,1);float dx=x-(ax+vx*t),dy=y-(ay+vy*t);return dx*dx+dy*dy<=r*r;}
 public static boolean lineBlockedByLevel(float ax,float ay,float bx,float by,Level level){return lineBlockedByLevel(ax,ay,bx,by,level,0f);} public static boolean lineBlockedByLevel(float ax,float ay,float bx,float by,Level level,float clearance){for(Wall w:level.getWalls())if(w.isBlocking()&&segmentIntersectsRect(ax,ay,bx,by,expanded(w.getBounds(),clearance)))return true;for(Door d:level.getDoors())if(d.isBlocking()&&segmentIntersectsRect(ax,ay,bx,by,expanded(d.getBounds(),clearance)))return true;return false;}
 private static RectF expanded(RectF r,float p){return new RectF(r.left-p,r.top-p,r.right+p,r.bottom+p);} private static boolean segmentIntersectsRect(float ax,float ay,float bx,float by,RectF r){int steps=Math.max(2,(int)(Math.hypot(bx-ax,by-ay)/12));for(int i=0;i<=steps;i++){float t=i/(float)steps;if(r.contains(ax+(bx-ax)*t,ay+(by-ay)*t))return true;}return false;} private static float clamp(float v,float min,float max){return Math.max(min,Math.min(max,v));}
}
